-- MySQL Script generated by MySQL Workbench
-- 07/04/14 20:47:24
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dormitory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dormitory` DEFAULT CHARACTER SET utf8 ;
USE `dormitory` ;

-- -----------------------------------------------------
-- Table `dormitory`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`room` (
  `roomID` INT(11) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `currentKW` FLOAT NOT NULL,
  `currentcubicmeter` FLOAT NOT NULL,
  `paidelectric` TINYINT(1) NULL,
  `paidwater` TINYINT(1) NULL,
  `paidrent` TINYINT(1) NULL,
  PRIMARY KEY (`roomID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormitory`.`tenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`tenant` (
  `tenantID` INT(11) NOT NULL,
  `tenant_roomID` INT(11) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `contact` INT(12) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `degree` VARCHAR(255) NOT NULL,
  `school` VARCHAR(255) NOT NULL,
  `expectedyearofgrad` INT(4) NOT NULL,
  `image` BLOB NOT NULL,
  PRIMARY KEY (`tenantID`),
  INDEX `roomID_idx` (`tenant_roomID` ASC),
  CONSTRAINT `tenant_roomID`
    FOREIGN KEY (`tenant_roomID`)
    REFERENCES `dormitory`.`room` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormitory`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`bill` (
  `billID` INT(11) NOT NULL,
  `bill_roomID` INT(11) NOT NULL,
  `billDate` DATE NOT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`billID`),
  INDEX `roomID_idx` (`bill_roomID` ASC),
  CONSTRAINT `bill_roomID`
    FOREIGN KEY (`bill_roomID`)
    REFERENCES `dormitory`.`room` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormitory`.`electric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`electric` (
  `electricID` INT(11) NOT NULL,
  `currentKW` FLOAT NOT NULL,
  `prevKW` FLOAT NOT NULL,
  `priceperKW` FLOAT NOT NULL,
  INDEX `billID_idx` (`electricID` ASC),
  CONSTRAINT `electricID`
    FOREIGN KEY (`electricID`)
    REFERENCES `dormitory`.`bill` (`billID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormitory`.`water`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`water` (
  `waterID` INT NOT NULL,
  `currentcubicpermeter` FLOAT NOT NULL,
  `prevcubicpermeter` FLOAT NOT NULL,
  `pricepercubicmeter` FLOAT NOT NULL,
  CONSTRAINT `waterID`
    FOREIGN KEY (`waterID`)
    REFERENCES `dormitory`.`bill` (`billID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormitory`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`contract` (
  `contract_tenantID` INT(11) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `dateofentry` DATE NOT NULL,
  `dateofexit` DATE NOT NULL,
  INDEX `tenantID_idx` (`contract_tenantID` ASC),
  CONSTRAINT `tenantID`
    FOREIGN KEY (`contract_tenantID`)
    REFERENCES `dormitory`.`tenant` (`tenantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormitory`.`guardian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`guardian` (
  `guardianID` INT(11) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `contact` INT(12) NOT NULL,
  PRIMARY KEY (`guardianID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormitory`.`tenantguardian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`tenantguardian` (
  `tg_tenantID` INT(11) NOT NULL,
  `tg_guardianID` INT(11) NOT NULL,
  INDEX `tenantID_idx` (`tg_tenantID` ASC),
  INDEX `guardianID_idx` (`tg_guardianID` ASC),
  CONSTRAINT `tg_tenantID`
    FOREIGN KEY (`tg_tenantID`)
    REFERENCES `dormitory`.`tenant` (`tenantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tg_guardianID`
    FOREIGN KEY (`tg_guardianID`)
    REFERENCES `dormitory`.`guardian` (`guardianID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormitory`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormitory`.`log` (
  `log_tenantID` INT(11) NOT NULL,
  `in` TIMESTAMP NOT NULL,
  `out` TIMESTAMP NULL,
  INDEX `tenantID_idx` (`log_tenantID` ASC),
  CONSTRAINT `log_tenantID`
    FOREIGN KEY (`log_tenantID`)
    REFERENCES `dormitory`.`tenant` (`tenantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
